export const siteConfig = {
  name: "Saarth Vardhan",
  tagline: "Product manager and data scientist building decision systems across enterprise technology, finance, and AI",
  subheadline: "NetApp Product · Columbia MSDS · Ex-Bain & Company",
  description: "Product management and data science portfolio spanning enterprise technology, AI systems, and analytics.",
  resumePath: "/documents/Saarth Vardhan - Resume.pdf",
  email: "sv2850@columbia.edu",
  phone: "+1 669 210 3462",
  linkedin: "https://www.linkedin.com/in/saarth-vardhan",
  github: "https://github.com/saarthv",
  substack: "https://substack.com/@saarthv",
  nav: [
    { href: "/", label: "Home" },
    { href: "/work", label: "Work" },
    { href: "/about", label: "About" },
    { href: "/blog", label: "Blog" },
    { href: "/resume", label: "Resume" },
    { href: "/contact", label: "Contact" },
  ],
};
